AllenInstitute/visual_behavior_analysis

- visual_behavior/database.py
* make more general for use with ecephys sessions
* set 'name' column as index
> improve well_known_file query

- visual_behavior/ophys/io/convert_level_1_to_level_2.py
- visual_behavior/visualization/extended_trials/daily.py
- visual_behavior/visualization/qc/dash_app/app.py
@dougollerenshaw I've modified make_daily_figure and make_rolling_dprime_plot to display both the adjusted and legacy dprime values. Let me know if this looks ok.
> add trial adjusted dprime to make_daily_figure

- visual_behavior/ophys/io/convert_level_1_to_level_2.py
hi marina; this is to make the convert code not fail on shutil related errors.
> shutil error; modifying exception so it works.

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
- visual_behavior/data_access/utilities.py
- visual_behavior/ophys/dataset/stimulus_processing.py
- visual_behavior/ophys/io/create_multi_session_mean_df.py
- visual_behavior/ophys/response_analysis/response_analysis.py
- visual_behavior/ophys/response_analysis/response_processing.py
- visual_behavior/ophys/response_analysis/utilities.py
adding separate functions to get response xarray for trials, omission and stimulus response, in addition to existing functions to get response dataframe
> add get_response_xr functions

- setup.cfg
- setup.py
- visual_behavior/__init__.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/utilities.py
- visual_behavior/database.py
- visual_behavior/ophys/io/convert_level_1_to_level_2.py
> refactor to break circular dependency

- visual_behavior/plotting.py
creates n random colors.
allows user to specify range of lightness and saturation values
allows user to sort by hue if desired (default is randomized hue)
> function to generate a random colormap

- .circleci/config.yml
- requirements.txt
- setup.py
- tests/ophys/test_io.py
- visual_behavior/metrics.py
- visual_behavior/utilities.py
- visual_behavior/visualization/extended_trials/mouse.py
Attempting to fix tests on a PR without any substantive code changes.
> a test PR to troubleshoot circleci issues

- requirements.txt
- setup.py
deals with version conflict on install
> update marshmallow to rc6 to match allensdk

- notebooks/200928_get_data_for_decoding.html
- notebooks/200928_get_data_for_decoding.ipynb
- scripts/concatenate_stimulus_presentations.py
- scripts/concatenate_stimulus_response_dfs.py
- scripts/run_concatenate_stimulus_presentations.py
- scripts/run_concatenate_stimulus_response_dfs.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/processing.py
Addresses issue with dataset.get_roi_masks() that was leading to misplacement of ROIs.
Before:
After:
> fix ROI misplacement issue

- visual_behavior/data_access/loading.py
Simplifies loading method by using cached CSVs instead of NPZ files
> update loading of behavior movie predictions

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
- visual_behavior/database.py
- visual_behavior/utilities.py
* Adds a tidy dff/f dataframe to the dataset object (augments the existing dataframe that has dff arrays stored inside a dataframe column)
* Adds functionality to the event triggered average function to return a tidy dataframe as an option
> add dF/F functionality

- visual_behavior/data_access/loading.py
Deals with mesoscope timestamp issue in addition to core issue with namespace
> Fixes issue 680

- scripts/create_multi_session_df.py
- scripts/run_create_multi_session_df.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
- visual_behavior/ophys/io/create_multi_session_df.py
- visual_behavior/ophys/response_analysis/response_analysis.py
- visual_behavior/visualization/ophys/population_summary_figures.py
- visual_behavior/visualization/utils.py
This fix is kind of hacky and should be temporary until mesoscope time resampling is implemented in SDK
> merge dev into master

- scripts/run_sdk_validation.py
- visual_behavior/validation/sdk.py
* adds a method to get behavior session table restricted to only valid sessions
* updates cluster deploy script
> SDK validation updates

- visual_behavior/data_access/loading.py
Gets useful columns from LIMS for every cell when the input is either:
* cell_specimen_ids
* ophys_experiment_ids
> SQL query in data_access.loading to get cell info from LIMS

- visual_behavior/data_access/loading.py
* typo fix, upated => updated
* convert joins to left joins
* fix syntax on single entry queries
> fixing issues with PR 689

- requirements.txt
- visual_behavior/utilities.py
Adds an example code block to the docstring for utilities.event_triggered_response
> add example docstring for utilities.event_triggered_response

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/utilities.py
- visual_behavior/ophys/response_analysis/response_analysis.py
- visual_behavior/ophys/response_analysis/response_processing.py
- visual_behavior/visualization/qc/compute_snr_metrics.py
- visual_behavior/visualization/qc/container_plots.py
- visual_behavior/visualization/qc/experiment_plots.py
- visual_behavior/visualization/qc/experiment_summary.py
using filtered events from dataset when filter_events set to True
> adding filter_events option

- README.md
adds section to README.md describing how to run tests locally
> update readme with testing howto

- tests/data_access/test_from_lims.py
- visual_behavior/data_access/from_lims.py
Creates on prem tests for the from_lims module.
> Create from lims tests

- README.md
added specific sections to testing:
-creating test virtual environments
- basic testing (external users)
- on premises testing (internal users)
-Linting
- running subset of tests
> updated README for more testing instructions

- visual_behavior/data_access/loading.py
updated the depreciation warning to include October 29th as the date of removal for many depreciated functions.
> updated the depreciation warnings for functions now found in from_lims

- visual_behavior/ophys/dataset/extended_stimulus_processing.py
> fixing #818
