- visual_behavior/change_detection/trials/summarize.py
- visual_behavior/visualization/extended_trials/mouse.py
I've added a new metric to the DEFAULT_SUMMARY_METRICS dictionary. Now when you call session_level_summary, you should get both d_prime_peak (the raw metric) and d_prime_peak_trial_adjusted (the adjusted metric). 
This should make it easy to display both metrics in mouse-seeks since now "get_full_summary_stats" in the ophys extractor change_detection dataset will return a dictionary with both of them.
> add trial adjusted d prime peak to default summary metrics

- setup.py
- visual_behavior/__init__.py
- visual_behavior/data_access/loading.py
- visual_behavior/ophys/response_analysis/response_analysis.py
Deals with this setting on copy warning regardless of whether invalid_ROIS are included (previous iteration was dependent on that). 
@dougollerenshaw you commented on the earlier draft whether there is an problem with ignoring the errors. That error I'm ignoring is just when the code is dropping a column, and it ignores the error if the column isnt there. I think its ok, because its one of those things where pandas sometimes makes the index a column when you reset the index, and sometimes it drops it.
> Silence warning

- visual_behavior/database.py
generalizes the `get_pkl_path` method for behavior only sessions. Previously this method only worked for ophys sessions
> generalize the `get_pkl_path` method for behavior only sessions

- visual_behavior/data_access/loading.py
The BehaviorOphysDataset had two related issues with how parameters were initialized. This PR fixes both of them, outlined in issue #660 
1. the `include_invalid_rois` parameter needed to be internally named `_include_invalid_rois` for the get/set parameter system to work. I checked all the files in the `data_access` module for name changes, but didnt check VBA beyond that module.
2. I dont understand why but the two eye_tracking parameters that are defined in the constructor `__init__` method for BehaviorOphysSession were not getting set when the BehaviorOphysDataset was created. So I explicitly call them in the call to the init() function, and that solves the problem!
> fixes get_params() issue

- tests/ophys/dataset/test_visual_behavior_ophys_dataset.py
- visual_behavior/data_access/utilities.py
Working with @DowntonCrabby to fix line label mismatch issue. Line labels in data_access/utilities for eye and behavior cameras were reversed from the convention outlined here:
https://github.com/AllenInstitute/AllenSDK/blob/be4dfb1dada2e8466ce1091e02d40a5ef17e7b15/allensdk/internal/brain_observatory/time_sync.py#L22
We updated VBA to match the SDK convention
> fix eye/behavior line labels to match SDK convention

- notebooks/stimulus_warping_example.ipynb
adds a notebook showing how to use the SDK `make_display_mask` function, which denotes which pixels will be visible on the screen after stimulus warping
> add notebook detailing stimulus warp

- requirements.txt
To avoid problems stemming from issue #696
We should unpin the SDK after #696 is resolved
> pin SDK at 2.3.2

- visual_behavior/data_access/loading.py
* fixes issue in data_access.loading.BehaviorOphysDataset that was leading to ambiguity in analysis folder (if ophys_experiment_id was passed as a float, a new folder would be created, leading to ambiguity)
* adds 'sdk_only' option to data_access.loading.get_ophys_data() to allow all extra processing in BehaviorOphysDataset. Default = False (maintains current behavior by default)
* adds 'verbose' option to data_access.loading.get_ophys_data(). If False (now default), suppresses print statement during loading process.
> fix data loading issues

- scripts/deploy_log_dff_stats.py
- scripts/log_dff_stats.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/processing.py
- visual_behavior/database.py
* adds a function to `data_access.processing` called `add_dff_stats_to_specimen_table` that takes the session object as the input and returns a cell_specimen_table with statistics on dff_traces appended (stats are provided by `pd.describe()` and include mean, std, 25%, 50%,75%, min, max)
* adds a script called `log_dff_stats.py` that will take an ophys_experiment_id as an input, call `add_dff_stats_to_specimen_table`, then log the resulting table to a mongo collection called `['ophys_data']['dff_summary']`
* adds a script called `deploy_log_dff_stats.py` that will iterate over the `filtered_ophys_experiment_table` and create one cluster job per experiment to execute `log_dff_stats.py`
* adds a function to `database.py` called `log_cell_dff_data` that handles writing of a single dff_stats …
> add code to build dff stats table

- tests/test_utilities.py
updated filepath for test_movie_load in test_utilities to include double slash at beginning of filepath to work with windows and linux filepaths
> updated test file path to work with windows and linux

- visual_behavior/data_access/utilities.py
- visual_behavior/database.py
* adds a new method to data_access.utilities which will query LIMS for all IDs given a single ID
Example use:
* adds options to various data_access.utilities queries that allow them to work without passing a cache. Instead, they go straight to LIMS. This should make them more convenient for internal users.
* modifies the query format in a single method in database.py
> Lims query changes

- visual_behavior/data_access/utilities.py
adds a function to data_access utilities to build a tidy dataframe with all cell activity observations.
For example, this:
```
from visual_behavior.data_access import loading
from visual_behavior.data_access import utilities as data_utilities
oeid = 993891850
session = loading.get_ophys_dataset(oeid)
cell_df = data_utilities.build_tidy_cell_df(session)
```
gives:
This is a prerequisite for caching cell data in mongo.
> add function to generate tidy dataframe describing cell activity

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
Add's columns for `engaged` (bool) and `engagement_state` (str, 'engaged' or 'disengaged') to the `extended_trials` table.
Example use:
```
from visual_behavior.data_access import loading
oeid = 958527474
dataset = loading.get_ophys_dataset(oeid)
dataset.extended_trials
```
The value of  `engaged` and `engagement_state` is taken from the stimulus in `extended_stimulus_presentations` that most closely aligns with the `start_time` of each trial.
Given that `extended_stimulus_presentations` must first be built, this function is slow.
> Add engagement to trials

- visual_behavior/data_access/loading.py
I moved from a csv file to a .pkl file for the summary table because I now include several columns that are arrays. These metrics don't load properly from csv. They include:
- the model weights
- image by image metrics like CR (every non change image without a lick), miss (change without lick), hit (change with a lick), FA (every non-change image with a lick). 
- image by image response time metric. This is bounded between (0, 750ms), and is the time between the start of each lick bout to the most recent image start. 
- image by image engaged/disengaged metric
- lick_bout_start (did a lick bout start during this image presentation?)
- lick_bout_rate (lick bouts/sec, averaged over 320 seconds)
- reward_rate (rewards/sec, averaged over 320 seconds)
- change (was this image a change image)
- …
> changing csv to pkl

- setup.cfg
- tests/data_access/test_reformat.py
- visual_behavior/data_access/reformat.py
fixes two bugs in `visual_behavior.data_access.reformat.add_engagement_state_to_trials_table`
1) replaces `np.argmin` with `pd.idxmin`: argmin worked when I developed the function, but has suddenly stopped working. I changed my pandas version, which might explain why. Regardless, idxmin should be more reliable
2) fixed double assignment
Also adds a test on `visual_behavior.data_access.reformat.add_engagement_state_to_trials_table`. 
Pinning hdmf at 2.4.0 to deal with this issue:
https://github.com/AllenInstitute/AllenSDK/issues/2098
> bugfixes in add_engagement_state_to_trials_table

- visual_behavior/data_access/from_lims.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/utilities.py
- visual_behavior/ophys/sync/process_sync.py
Updates lines of code in data_access.loading to use updated code in data_access.from_lims to convert ophys_experiment_id top ophys_session_id.
Fixes issue #747.
Also maybe related to this issue in the GLM:
AllenInstitute/visual_behavior_glm#247
Also fixes issue #750:
Removes unnecessary print statement in data_access.utilities that said `resampling mesoscope 2P frame times` and casts experiment_id to int to avoid warnings about numpy.int64 type in LIMS queries.
And also fixes issue #751: makes sync photodiode error printout optional (suppressed by default). Since the display lag is now being calculated by the SDK, I don't think that it's important for VBA to be reporting problems now.
> fix broken experiment_id to session_id code and limit stdout warnings/prints

- visual_behavior/data_access/loading.py
Adds a function to data_access/loading called `get_cell_table` that will return data from the LIMS `cell_rois` table for specified experiments. If no experiments are passed, it returns all released cells.
Details and examples in the docstring.
> adding function to get cell_specimen table from LIMS

- visual_behavior/data_access/loading.py
Addresses issue #756. 
Calls `reset_index` on `get_released_ophys_experiment_table`. The `ophys_experiment_id` column is subsequently set as the index on line 204.
> bug fix in visual_behavior/data_access/loading.py

- tests/data_access/test_from_lims.py
- visual_behavior/data_access/from_lims.py
- visual_behavior/data_access/loading.py
This PR adds a new function that will check the ID type when passed a LIMS ID. That will let us quickly check to ensure that the correct ID type is passed to a given function. Here are some example use cases:
```python
>> get_id_type(914580664)
'ophys_experiment_id'
>> get_id_type(914211263)
'behavior_session_id'
>> get_id_type(1086515263)
'cell_specimen_id'
>> get_id_type(914161594)
'ophys_session_id'
>> get_id_type(1080784881)
'cell_roi_id'
>> get_id_type(1234)
'unknown_id'
```
The above examples are added as unit tests.
I added some logic to `loading.get_ophys_dataset` that will ensure that the passed ID is indeed an `ophys_experiment_id`. If not, it will throw a warning, then fail with an assertion error. This will stop the dreaded mystery crashes that are something 'One resulted …
> Function for checking id type

- visual_behavior/data_access/loading.py
This PR breaks `load_behavior_model_outputs` into a distinct function in data_access.loading.
Making this function available on its own facilitates loading just the model outputs if desired.
The `add_model_outputs_to_stimulus_presentations` function now uses `load_behavior_model_outputs`
> Break out behavior model function

- visual_behavior/data_access/from_lims.py
Adds a function to data_access.from_lims to get the genotype for a given experiment_id
Example:
```python
from visual_behavior.data_access import from_lims
from_lims.get_genotype_from_ophys_experiment_id(1071070929)
```
Returns:
`'Vip-IRES-Cre/wt;Ai148(TIT2L-GC6f-ICL-tTA2)/wt'`
> adding a function to get cre line from experiment ID

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
- visual_behavior/data_access/utilities.py
Functions to add new columns to the experiments table that can be used to select data for platform paper analysis, instead of using 'session_type'. 
For example, the experiment_table returned from loading.get_filtered_ophys_experiment_table() will now contain an "experience_level" column that contains the strings ['Familiar', 'Novel 1', Novel >1'] 
There is also a 'passive' column with a Boolean for whether a session was passive or not. 
There is also a function called add_cell_type which creates a column with values to use instead of cre_line for plots: ['Excitatory', 'Sst Inhibitory', 'Vip Inhibitory']
> add new condition labels to experiments table

- visual_behavior/data_access/loading.py
the get_cell_table function has ophys_session_ids as an input param when it really wants ophys_experiment_ids. this PR fixes that.
> update input param name to get_cell_tabe

- visual_behavior/data_access/loading.py
`data_access/loading.py` was broken by recent SDK updates. I removed the outdated calls. Previously several functions let users pull sessions using lims, nwb, or confusingly, through the lims API. I removed that last option since it no longer exists. I did not check for other instances of these outdated classes, or other outdated classes in this module.
> removing outdated SDK classes

- visual_behavior/data_access/loading.py
Adds `add_extra_columns=True` as optional argument to two functions that in-turn call `get_platform_paper_experiment_table` just in case you want to turn off adding the extra columns.
> adding ability to not add extra columns to cell table

- scripts/cache_behavior_performance_for_all_sessions.py
- scripts/cache_behavior_performance_for_one_session.py
- visual_behavior/data_access/loading.py
- visual_behavior/data_access/reformat.py
- visual_behavior/data_access/utilities.py
- visual_behavior/utilities.py
goal was to save performance metrics that Doug computed, but his code didnt run as is, presumably because things have changed since. i made several updates to get the code to run, including computing engagement based on reward rate in get_extended_stimulus_presentations directly, instead of loading from behavior model output files. 
currently testing that it all works on the cluster, there may be a few additional tweaks before it is ready to merge.
> update extended stim and trials to generate and cache behavior metrics

- setup.cfg
- Resolves #810 
- Pinning `markupsafe` version used in testing to `2.0.1` following the advice on https://github.com/aws/aws-sam-cli/issues/3661
> Fix circleci

- setup.cfg
- visual_behavior/data_access/reformat.py
- visual_behavior/data_access/utilities.py
- See PR #811 for details
There were three functions in `utilities` that used `loading`. 
- This is a duplicate!?!? of `loading.check_if_model_output_available` so I am removing this function
- This is a duplicate!?!? of `loading.check_if_model_output_available` so I am removing this function
- Called by `reformat.add_model_outputs_availability_to_table()` 
- in turn called by `reformat_experiments_table()`. So I removed that function call. 
- On slack @matchings says its ok to remove this function, so I am removing it.
> Fixing circular imports and CircleCI tests

- visual_behavior/data_access/reformat.py
`data_access.reformat.add_time_since_last_change` used an outdated column name `change`. Here I rename it to use `is_change`.
> renaming change to is_change

- visual_behavior/visualization/utils.py
PR #804 added a `sns.set_context()` call in `visualization/utils` that caused plots to look unexpectedly different. I'm removing that `set_context()` call. 
- Resolves https://github.com/AllenInstitute/visual_behavior_glm/issues/434
> removing sns.set_context

- visual_behavior/ophys/dataset/extended_stimulus_processing.py
`esp.licks_each_flash` and `esp.rewards_each_flash` annotate the rows of `session.stimulus_presentations` with the licks and rewards that happen during each flash. Currently they look for strict inclusion with a set time range relative to the stimulus onset. If the lick or reward happens at exactly the moment the stimulus starts the lick or reward is not assigned to any stimulus. I've fixed that by making the test of for the start of the time range inclusive ">=" rather than ">"
> Fixes an edge case in extended_stimulus_processing.licks_each_flash

- setup.cfg
addresses #822
h5py and umap are top level dependencies (but not pytables). Seems like best practices to keep install_requires to this level? Should be sufficient to prevent the import issues you described (FWIW pytables and h5py were install by pip when I did the usual setup.py, on the version before this commit).
> update requires with umap and h5py

- visual_behavior/data_access/loading.py
- visual_behavior/data_access/utilities.py
because only ophys sessions have a `project_code `in the `behavior_sessions `table, the `VisualBehaviorMultiscope4x2 `behavior training sessions were not being properly filtered out in the `get_platform_paper_behavior_session_table` function. This PR adds a step to merge the `project_codes `from the `ophys_experiment_table `into the `behavior_sessions `table before filtering out the 4x2 sessions. 
As part of this PR, the `get_platform_paper_behavior_session_table `function was also updated to add an `experience_level` column that matches the `ophys_experiments_table `values (Novel 1, Novel >1, Familiar) for ophys sessions, and adds new values for training sessions such that training sessions with gratings have `experience_level`='Gratings', training sessions with images have …
> get_platform_behavior_sessions was incorrectly filtering out 4x2

- visual_behavior/data_access/loading.py
- visual_behavior/database.py
- visual_behavior/utilities.py
- visual_behavior/validation/extended_trials.py
- I do this by removing the import of `visual_behavior.visualization.behavior` which breaks the function `visual_behavior.utilities.cache_response_probability()`
- I specifically am not fixing the linting issue caused by removing this import
> Fixing path and circular imports
